# TODO: Configure these values for your SonarCloud project
sonar.projectKey=micnussb17_cd-mcm-exercise-nussbaumer
sonar.organization=micnussb17

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.sourceEncoding=UTF-8
